# Generated by Django 5.2.6 on 2025-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100)),
                ('genero_animal', models.CharField(max_length=20)),
                ('porte_animal', models.CharField(choices=[('Grande Porte', 'Grande Porte'), ('Pequeno Porte', 'Pequeno Porte')], default='Pequeno Porte', max_length=20)),
                ('classificacao_animal', models.CharField(choices=[('Bovino', 'Bovino'), ('Suíno', 'Suíno'), ('Caprino', 'Caprino'), ('Ovino', 'Ovino'), ('Equino', 'Equino'), ('Outro', 'Outro')], max_length=20)),
                ('identificacao_animal', models.CharField(max_length=20)),
                ('foto_animal', models.ImageField(blank=True, upload_to='animais/media/')),
                ('vacinas_animal', models.ImageField(blank=True, upload_to='animais/media/')),
                ('observacao_animal', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
