# Generated by Django 5.2.6 on 2025-10-18 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AddField(
            model_name='animal',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='animal',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='classificacao_animal',
            field=models.CharField(choices=[('B', 'Bovino'), ('S', 'Suíno'), ('C', 'Caprino'), ('O', 'Ovino'), ('E', 'Equino'), ('X', 'Outro')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto_animal',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genero_animal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identificacao_animal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte_animal',
            field=models.CharField(choices=[('G', 'Grande Porte'), ('P', 'Pequeno Porte')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacinas_animal',
            field=models.ImageField(blank=True, null=True, upload_to='animais/vacinas/'),
        ),
    ]
