# Generated by Django 5.2.6 on 2025-10-18 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_options_animal_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='genero_animal',
            field=models.CharField(choices=[('M', 'Masculino'), ('W', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='modificado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
