# Generated by Django 5.2.6 on 2025-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_animal_genero_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='classificacao_animal',
            field=models.CharField(choices=[('B', 'Bovino'), ('S', 'Suíno'), ('C', 'Caprino'), ('O', 'Ovino'), ('E', 'Equino'), ('X', 'Outro')], default='B', max_length=1),
        ),
    ]
