# Generated by Django 5.2.6 on 2025-12-08 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_alter_animal_classificacao_animal'),
        ('fazendas', '0003_alter_fazenda_options_alter_fazenda_foto_fazenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fazendas.fazenda'),
        ),
    ]
