# Generated by Django 5.2.6 on 2026-02-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_alter_animal_fazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='porte_animal',
            field=models.CharField(choices=[('G', 'Grande Porte'), ('A', 'Médio Porte'), ('P', 'Pequeno Porte')], default='A', max_length=1),
        ),
    ]
