# Generated by Django 5.2.6 on 2025-10-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100)),
                ('genero_animal', models.CharField(max_length=20)),
                ('porte_animal', models.CharField(choices=[('Grande Porte', 'Grande Porte'), ('Pequeno Porte', 'Pequeno Porte')], default='Pequeno Porte', max_length=20)),
                ('classificacao_animal', models.CharField(choices=[('Bovino', 'Bovino'), ('Suíno', 'Suíno'), ('Caprino', 'Caprino'), ('Ovino', 'Ovino'), ('Equino', 'Equino'), ('Outro', 'Outro')], max_length=20)),
                ('identificacao_animal', models.CharField(max_length=20)),
                ('foto_animal', models.ImageField(blank=True, upload_to='rumix/media/')),
                ('vacinas_animal', models.ImageField(blank=True, upload_to='rumix/media/')),
                ('observacao_animal', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fazenda', models.CharField(max_length=100)),
                ('foto_fazenda', models.ImageField(blank=True, upload_to='rumix/media/', verbose_name='Imagem da fazenda')),
                ('sobre_fazenda', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('dono_fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fazendas',
            },
        ),
    ]
