# Generated by Django 5.2.6 on 2025-10-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumix', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Fazenda',
        ),
    ]
