# Generated by Django 5.2.6 on 2025-10-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fazenda',
            old_name='dono',
            new_name='dono_fazenda',
        ),
    ]
