# Generated by Django 5.2.6 on 2025-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0002_rename_dono_fazenda_dono_fazenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='foto_fazenda',
            field=models.ImageField(blank=True, null=True, upload_to='fazendas/media/', verbose_name='Imagem da fazenda'),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='nome_fazenda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='sobre_fazenda',
            field=models.TextField(),
        ),
    ]
